# Generated by Django 2.2 on 2024-07-31 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='now_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='total_balance',
        ),
        migrations.RemoveField(
            model_name='user',
            name='total_deposits',
        ),
        migrations.RemoveField(
            model_name='user',
            name='total_profits',
        ),
        migrations.RemoveField(
            model_name='user',
            name='total_withdraws',
        ),
    ]
